test:
  image: node:12
  before_script:
    - npm config set cache "$(pwd)/.npm"
    - npm install
  script:
    - yarn run dev
    - yarn run build --coverage
    - yarn run markdownlint
    # Make sure build output has been committed.
    - git status --porcelain || (echo "Repo is dirty"; git diff; false)
  cache:
    paths:
      - node_modules
      - .npm
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: coverage/junit.xml
    paths:
      - coverage
