services:
  grafana:
    user: "${UID:-root}:${GID:-root}"
    container_name: 'fetzerch-sunandmoon-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/fetzerch-sunandmoon-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/fetzerch-sunandmoon-datasource
      # Persist Grafana settings.
      #- ./data:/var/lib/grafana

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.fetzerch-sunandmoon-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fetzerch-sunandmoon-datasource
